[project]
name = "temporalvoicesdk"
version = "0.1.0"
description = "Temporal Voice SDK - Voice Analytics and Pattern Recognition Tools"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "numpy",
    "pandas",
    "plotly",
    "speechrecognition"
]
requires-python = ">=3.8"
