# This workflow will automatically build and publish the TemporalVoiceSDK package to PyPI
# when a new release is published on GitHub.

name: Publish TemporalVoiceSDK to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    name: Build TemporalVoiceSDK
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools and build package
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: temporalvoicesdk-dist
          path: dist/

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  # Needed for trusted publishing

    environment:
      name: pypi
      url: https://pypi.org/project/temporalvoicesdk/${{ github.event.release.tag_name }}

    steps:
      - name: Download distribution artifacts
        uses: actions/download-artifact@v4
        with:
          name: temporalvoicesdk-dist
          path: dist/

      - name: Publish to PyPI via Trusted Publishing
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
